core:
  prefix: "[EVENT] "
  event: "EventDefault"
  debug-exceptions: false
#

data:
  mongo:
    host : "127.0.0.1"
    port : 27017
    user : "minecraft"
    password : "admin"
    db : "admin"
    databases : ["master"]
  rabbitMQ:
    debug : false
    host : "127.0.0.1"
    port : 5672
    user : "minecraft"
    password : "admin"
    exchange : "minecraft"
    consumer:
      queue : "bot-output"
      routingKey : "bot-output"
    publisher:
      queue : "bot-input"
      rootingKey : "bot-input"
#